// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zohar/sample/agares.proto

package com.xenoblade.zohar.sample.agares.api;

public final class Agares {
  private Agares() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HelloAgaresRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zohar.sample.HelloAgaresRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code zohar.sample.HelloAgaresRequest}
   */
  public  static final class HelloAgaresRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zohar.sample.HelloAgaresRequest)
      HelloAgaresRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloAgaresRequest.newBuilder() to construct.
    private HelloAgaresRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloAgaresRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloAgaresRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xenoblade.zohar.sample.agares.api.Agares.internal_static_zohar_sample_HelloAgaresRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xenoblade.zohar.sample.agares.api.Agares.internal_static_zohar_sample_HelloAgaresRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest.class, com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest)) {
        return super.equals(obj);
      }
      com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest other = (com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zohar.sample.HelloAgaresRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zohar.sample.HelloAgaresRequest)
        com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xenoblade.zohar.sample.agares.api.Agares.internal_static_zohar_sample_HelloAgaresRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xenoblade.zohar.sample.agares.api.Agares.internal_static_zohar_sample_HelloAgaresRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest.class, com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest.Builder.class);
      }

      // Construct using com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xenoblade.zohar.sample.agares.api.Agares.internal_static_zohar_sample_HelloAgaresRequest_descriptor;
      }

      public com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest getDefaultInstanceForType() {
        return com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest.getDefaultInstance();
      }

      public com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest build() {
        com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest buildPartial() {
        com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest result = new com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest) {
          return mergeFrom((com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest other) {
        if (other == com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zohar.sample.HelloAgaresRequest)
    }

    // @@protoc_insertion_point(class_scope:zohar.sample.HelloAgaresRequest)
    private static final com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest();
    }

    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloAgaresRequest>
        PARSER = new com.google.protobuf.AbstractParser<HelloAgaresRequest>() {
      public HelloAgaresRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloAgaresRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloAgaresRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloAgaresRequest> getParserForType() {
      return PARSER;
    }

    public com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HelloAgaresResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zohar.sample.HelloAgaresResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string response = 1;</code>
     */
    java.lang.String getResponse();
    /**
     * <code>string response = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseBytes();

    /**
     * <code>int32 errorcode = 2;</code>
     */
    int getErrorcode();
  }
  /**
   * Protobuf type {@code zohar.sample.HelloAgaresResponse}
   */
  public  static final class HelloAgaresResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zohar.sample.HelloAgaresResponse)
      HelloAgaresResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloAgaresResponse.newBuilder() to construct.
    private HelloAgaresResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloAgaresResponse() {
      response_ = "";
      errorcode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloAgaresResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              response_ = s;
              break;
            }
            case 16: {

              errorcode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xenoblade.zohar.sample.agares.api.Agares.internal_static_zohar_sample_HelloAgaresResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xenoblade.zohar.sample.agares.api.Agares.internal_static_zohar_sample_HelloAgaresResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse.class, com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private volatile java.lang.Object response_;
    /**
     * <code>string response = 1;</code>
     */
    public java.lang.String getResponse() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        response_ = s;
        return s;
      }
    }
    /**
     * <code>string response = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseBytes() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        response_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private int errorcode_;
    /**
     * <code>int32 errorcode = 2;</code>
     */
    public int getErrorcode() {
      return errorcode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, response_);
      }
      if (errorcode_ != 0) {
        output.writeInt32(2, errorcode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, response_);
      }
      if (errorcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errorcode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse)) {
        return super.equals(obj);
      }
      com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse other = (com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse) obj;

      boolean result = true;
      result = result && getResponse()
          .equals(other.getResponse());
      result = result && (getErrorcode()
          == other.getErrorcode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorcode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zohar.sample.HelloAgaresResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zohar.sample.HelloAgaresResponse)
        com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xenoblade.zohar.sample.agares.api.Agares.internal_static_zohar_sample_HelloAgaresResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xenoblade.zohar.sample.agares.api.Agares.internal_static_zohar_sample_HelloAgaresResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse.class, com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse.Builder.class);
      }

      // Construct using com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        response_ = "";

        errorcode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xenoblade.zohar.sample.agares.api.Agares.internal_static_zohar_sample_HelloAgaresResponse_descriptor;
      }

      public com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse getDefaultInstanceForType() {
        return com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse.getDefaultInstance();
      }

      public com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse build() {
        com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse buildPartial() {
        com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse result = new com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse(this);
        result.response_ = response_;
        result.errorcode_ = errorcode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse) {
          return mergeFrom((com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse other) {
        if (other == com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse.getDefaultInstance()) return this;
        if (!other.getResponse().isEmpty()) {
          response_ = other.response_;
          onChanged();
        }
        if (other.getErrorcode() != 0) {
          setErrorcode(other.getErrorcode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object response_ = "";
      /**
       * <code>string response = 1;</code>
       */
      public java.lang.String getResponse() {
        java.lang.Object ref = response_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          response_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string response = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseBytes() {
        java.lang.Object ref = response_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          response_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response = 1;</code>
       */
      public Builder setResponse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string response = 1;</code>
       */
      public Builder clearResponse() {
        
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }
      /**
       * <code>string response = 1;</code>
       */
      public Builder setResponseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        response_ = value;
        onChanged();
        return this;
      }

      private int errorcode_ ;
      /**
       * <code>int32 errorcode = 2;</code>
       */
      public int getErrorcode() {
        return errorcode_;
      }
      /**
       * <code>int32 errorcode = 2;</code>
       */
      public Builder setErrorcode(int value) {
        
        errorcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 errorcode = 2;</code>
       */
      public Builder clearErrorcode() {
        
        errorcode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zohar.sample.HelloAgaresResponse)
    }

    // @@protoc_insertion_point(class_scope:zohar.sample.HelloAgaresResponse)
    private static final com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse();
    }

    public static com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloAgaresResponse>
        PARSER = new com.google.protobuf.AbstractParser<HelloAgaresResponse>() {
      public HelloAgaresResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloAgaresResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloAgaresResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloAgaresResponse> getParserForType() {
      return PARSER;
    }

    public com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code zohar.sample.AgaresService}
   */
  public static abstract class AgaresService
      implements com.google.protobuf.Service {
    protected AgaresService() {}

    public interface Interface {
      /**
       * <code>rpc HelloAgares(.zohar.sample.HelloAgaresRequest) returns (.zohar.sample.HelloAgaresResponse);</code>
       */
      public abstract void helloAgares(
          com.google.protobuf.RpcController controller,
          com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest request,
          com.google.protobuf.RpcCallback<com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new AgaresService() {
        @java.lang.Override
        public  void helloAgares(
            com.google.protobuf.RpcController controller,
            com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest request,
            com.google.protobuf.RpcCallback<com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse> done) {
          impl.helloAgares(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.helloAgares(controller, (com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc HelloAgares(.zohar.sample.HelloAgaresRequest) returns (.zohar.sample.HelloAgaresResponse);</code>
     */
    public abstract void helloAgares(
        com.google.protobuf.RpcController controller,
        com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest request,
        com.google.protobuf.RpcCallback<com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.xenoblade.zohar.sample.agares.api.Agares.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.helloAgares(controller, (com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest)request,
            com.google.protobuf.RpcUtil.<com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.xenoblade.zohar.sample.agares.api.Agares.AgaresService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void helloAgares(
          com.google.protobuf.RpcController controller,
          com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest request,
          com.google.protobuf.RpcCallback<com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse.class,
            com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse helloAgares(
          com.google.protobuf.RpcController controller,
          com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse helloAgares(
          com.google.protobuf.RpcController controller,
          com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.xenoblade.zohar.sample.agares.api.Agares.HelloAgaresResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:zohar.sample.AgaresService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zohar_sample_HelloAgaresRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zohar_sample_HelloAgaresRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zohar_sample_HelloAgaresResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zohar_sample_HelloAgaresResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031zohar/sample/agares.proto\022\014zohar.sampl" +
      "e\032\027zohar/sample/enum.proto\"\024\n\022HelloAgare" +
      "sRequest\":\n\023HelloAgaresResponse\022\020\n\010respo" +
      "nse\030\001 \001(\t\022\021\n\terrorcode\030\002 \001(\0052e\n\rAgaresSe" +
      "rvice\022T\n\013HelloAgares\022 .zohar.sample.Hell" +
      "oAgaresRequest\032!.zohar.sample.HelloAgare" +
      "sResponse\"\000B4\n%com.xenoblade.zohar.sampl" +
      "e.agares.apiB\006AgaresP\000\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xenoblade.zohar.sample.api.Enum.getDescriptor(),
        }, assigner);
    internal_static_zohar_sample_HelloAgaresRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zohar_sample_HelloAgaresRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zohar_sample_HelloAgaresRequest_descriptor,
        new java.lang.String[] { });
    internal_static_zohar_sample_HelloAgaresResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zohar_sample_HelloAgaresResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zohar_sample_HelloAgaresResponse_descriptor,
        new java.lang.String[] { "Response", "Errorcode", });
    com.xenoblade.zohar.sample.api.Enum.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
