<?xml version="1.0"  encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <parent>
    <groupId>org.zohar</groupId>
    <artifactId>zohar-core-plugin-example</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>zohar-core-plugin-example-api</artifactId>
  <name>Zohar Core Plugin Example Api</name>
  <packaging>jar</packaging>

  <dependencies>

    <dependency>
      <groupId>org.zohar</groupId>
      <artifactId>zohar-core-plugin-core</artifactId>
    </dependency>

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <compilerArgument>-proc:none</compilerArgument>
        </configuration>
        <executions>
          <execution>
            <id>default-compile</id>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>