// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zohar/sample/enum.proto

package com.xenoblade.zohar.sample.api;

public final class Enum {
  private Enum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code zohar.sample.EEnable}
   */
  public enum EEnable
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DISABLED = 0;</code>
     */
    DISABLED(0),
    /**
     * <code>ENABLED = 1;</code>
     */
    ENABLED(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DISABLED = 0;</code>
     */
    public static final int DISABLED_VALUE = 0;
    /**
     * <code>ENABLED = 1;</code>
     */
    public static final int ENABLED_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EEnable valueOf(int value) {
      return forNumber(value);
    }

    public static EEnable forNumber(int value) {
      switch (value) {
        case 0: return DISABLED;
        case 1: return ENABLED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EEnable>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EEnable> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EEnable>() {
            public EEnable findValueByNumber(int number) {
              return EEnable.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xenoblade.zohar.sample.api.Enum.getDescriptor().getEnumTypes().get(0);
    }

    private static final EEnable[] VALUES = values();

    public static EEnable valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EEnable(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:zohar.sample.EEnable)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027zohar/sample/enum.proto\022\014zohar.sample*" +
      "$\n\007EEnable\022\014\n\010DISABLED\020\000\022\013\n\007ENABLED\020\001B(\n" +
      "\036com.xenoblade.zohar.sample.apiB\004EnumP\000b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
