// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zohar/sample/errorcode.proto

package com.xenoblade.zohar.sample.api;

public final class ErrorCode {
  private ErrorCode() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code zohar.sample.EErrorCode}
   */
  public enum EErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知错误
     * </pre>
     *
     * <code>INVALID = 0;</code>
     */
    INVALID(0),
    /**
     * <pre>
     * 601 ~ 699 baal error
     * </pre>
     *
     * <code>BAAL_ERROR = 601;</code>
     */
    BAAL_ERROR(601),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 未知错误
     * </pre>
     *
     * <code>INVALID = 0;</code>
     */
    public static final int INVALID_VALUE = 0;
    /**
     * <pre>
     * 601 ~ 699 baal error
     * </pre>
     *
     * <code>BAAL_ERROR = 601;</code>
     */
    public static final int BAAL_ERROR_VALUE = 601;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EErrorCode valueOf(int value) {
      return forNumber(value);
    }

    public static EErrorCode forNumber(int value) {
      switch (value) {
        case 0: return INVALID;
        case 601: return BAAL_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EErrorCode>() {
            public EErrorCode findValueByNumber(int number) {
              return EErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xenoblade.zohar.sample.api.ErrorCode.getDescriptor().getEnumTypes().get(0);
    }

    private static final EErrorCode[] VALUES = values();

    public static EErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:zohar.sample.EErrorCode)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034zohar/sample/errorcode.proto\022\014zohar.sa" +
      "mple**\n\nEErrorCode\022\013\n\007INVALID\020\000\022\017\n\nBAAL_" +
      "ERROR\020\331\004B-\n\036com.xenoblade.zohar.sample.a" +
      "piB\tErrorCodeP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
