
spring:
  flyway:
    clean-disabled: true
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    encoding: utf-8
    table: zohar_schema_history
    out-of-order: true
    schemas: zohar_demo


zohar:
  datasource:
    dynamic:
      p6spy: true
      #      druid: #以下是全局默认值，可以全局更改
      #        initial-size:
      #        max-active:
      #        min-idle:
      #        max-wait:
      #        time-between-eviction-runs-millis:
      #        time-between-log-stats-millis:
      #        stat-sqlmax-size:
      #        min-evictable-idle-time-millis:
      #        max-evictable-idle-time-millis:
      #        test-while-idle:
      #        test-on-borrow:
      #        test-on-return:
      #        validation-query:
      #        validation-query-timeout:
      #        use-global-datasource-stat:
      #        async-init:
      #        clear-filters-enable:
      #        reset-stat-enable:
      #        not-full-timeout-retry-count:
      #        max-wait-thread-count:
      #        fail-fast:
      #        phyTimeout-millis:
      #        keep-alive:
      #        pool-prepared-statements:
      #        init-variants:
      #        init-global-variants:
      #        use-unfair-lock:
      #        kill-when-socket-read-timeout:
      #        connection-properties:
      #        max-pool-prepared-statement-per-connection-size:
      #        init-connection-sqls:
      #        share-prepared-statements:
      #        connection-errorretry-attempts:
      #        break-after-acquire-failure:
      #        filters: stat,wall # 注意这个值和druid原生不一致，默认启动了stat,wall
      druid:
        filters: stat
        initialSize: 2
        maxActive: 300
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSiz: 200
      datasource:
        master:
          username: sa
          password:
          url: jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS zohar_demo
          driver-class-name: org.h2.Driver
          druid: #这里可以重写默认值
            initial-size: 5
            init-connection-sqls: SET SCHEMA zohar_demo

mybatis-plus:
  type-aliases-package: com.xenoblade.zohar.sample.baal.entity
#  configuration:
#    auto-mapping-unknown-column-behavior: failing
##  global-config:
##    db-config:
##      id-type: auto
  mapper-locations: classpath:mapper/*Mapper.xml


logging:
  level:
    com.xenoblade: debug
