
spring:
  application:
    name: zohar-sample-baal
  flyway:
    clean-disabled: true
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    encoding: utf-8
    table: zohar_schema_history
    out-of-order: true
    schemas: zohar_demo


zohar:
  datasource:
    dynamic:
      p6spy: true
      #      druid: #以下是全局默认值，可以全局更改
      #        initial-size:
      #        max-active:
      #        min-idle:
      #        max-wait:
      #        time-between-eviction-runs-millis:
      #        time-between-log-stats-millis:
      #        stat-sqlmax-size:
      #        min-evictable-idle-time-millis:
      #        max-evictable-idle-time-millis:
      #        test-while-idle:
      #        test-on-borrow:
      #        test-on-return:
      #        validation-query:
      #        validation-query-timeout:
      #        use-global-datasource-stat:
      #        async-init:
      #        clear-filters-enable:
      #        reset-stat-enable:
      #        not-full-timeout-retry-count:
      #        max-wait-thread-count:
      #        fail-fast:
      #        phyTimeout-millis:
      #        keep-alive:
      #        pool-prepared-statements:
      #        init-variants:
      #        init-global-variants:
      #        use-unfair-lock:
      #        kill-when-socket-read-timeout:
      #        connection-properties:
      #        max-pool-prepared-statement-per-connection-size:
      #        init-connection-sqls:
      #        share-prepared-statements:
      #        connection-errorretry-attempts:
      #        break-after-acquire-failure:
      #        filters: stat,wall # 注意这个值和druid原生不一致，默认启动了stat,wall
      druid:
        filters: stat
        initialSize: 2
        maxActive: 300
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 200
      datasource:
        master:
          username: sa
          password:
          url: jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS zohar_demo
          driver-class-name: org.h2.Driver
          druid: #这里可以重写默认值
            initial-size: 5
            init-connection-sqls: SET SCHEMA zohar_demo

mybatis-plus:
  type-aliases-package: com.xenoblade.zohar.sample.baal.entity
#  configuration:
#    auto-mapping-unknown-column-behavior: failing
##  global-config:
##    db-config:
##      id-type: auto
#  mapper-locations: classpath:mapper/*Mapper.xml


logging:
  level:
    com.xenoblade: debug


server:
  port: 8081
  servlet:
    context-path: /baal
  # 下面是配置undertow作为服务器的参数
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

dubbo:
  application:
    name: baal-client
  scan:
    base-packages: com.xenoblade.zohar.sample.baal.service.dubbo
  protocol:
    name: dubbo
    port: 12346
    serialization: protostuff
    server: netty4
    client: netty4
  registry:
    address: N/A

