// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zohar/sample/baal.proto

package com.xenoblade.zohar.sample.baal.api;

public final class Baal {
  private Baal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HelloBaalRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zohar.sample.HelloBaalRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string request = 1;</code>
     */
    java.lang.String getRequest();
    /**
     * <code>string request = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestBytes();
  }
  /**
   * Protobuf type {@code zohar.sample.HelloBaalRequest}
   */
  public  static final class HelloBaalRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zohar.sample.HelloBaalRequest)
      HelloBaalRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloBaalRequest.newBuilder() to construct.
    private HelloBaalRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloBaalRequest() {
      request_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloBaalRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              request_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xenoblade.zohar.sample.baal.api.Baal.internal_static_zohar_sample_HelloBaalRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xenoblade.zohar.sample.baal.api.Baal.internal_static_zohar_sample_HelloBaalRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest.class, com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest.Builder.class);
    }

    public static final int REQUEST_FIELD_NUMBER = 1;
    private volatile java.lang.Object request_;
    /**
     * <code>string request = 1;</code>
     */
    public java.lang.String getRequest() {
      java.lang.Object ref = request_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        request_ = s;
        return s;
      }
    }
    /**
     * <code>string request = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestBytes() {
      java.lang.Object ref = request_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        request_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, request_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, request_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest)) {
        return super.equals(obj);
      }
      com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest other = (com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest) obj;

      boolean result = true;
      result = result && getRequest()
          .equals(other.getRequest());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getRequest().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zohar.sample.HelloBaalRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zohar.sample.HelloBaalRequest)
        com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xenoblade.zohar.sample.baal.api.Baal.internal_static_zohar_sample_HelloBaalRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xenoblade.zohar.sample.baal.api.Baal.internal_static_zohar_sample_HelloBaalRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest.class, com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest.Builder.class);
      }

      // Construct using com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        request_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xenoblade.zohar.sample.baal.api.Baal.internal_static_zohar_sample_HelloBaalRequest_descriptor;
      }

      public com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest getDefaultInstanceForType() {
        return com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest.getDefaultInstance();
      }

      public com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest build() {
        com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest buildPartial() {
        com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest result = new com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest(this);
        result.request_ = request_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest) {
          return mergeFrom((com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest other) {
        if (other == com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest.getDefaultInstance()) return this;
        if (!other.getRequest().isEmpty()) {
          request_ = other.request_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object request_ = "";
      /**
       * <code>string request = 1;</code>
       */
      public java.lang.String getRequest() {
        java.lang.Object ref = request_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          request_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string request = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestBytes() {
        java.lang.Object ref = request_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          request_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string request = 1;</code>
       */
      public Builder setRequest(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        request_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string request = 1;</code>
       */
      public Builder clearRequest() {
        
        request_ = getDefaultInstance().getRequest();
        onChanged();
        return this;
      }
      /**
       * <code>string request = 1;</code>
       */
      public Builder setRequestBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        request_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zohar.sample.HelloBaalRequest)
    }

    // @@protoc_insertion_point(class_scope:zohar.sample.HelloBaalRequest)
    private static final com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest();
    }

    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloBaalRequest>
        PARSER = new com.google.protobuf.AbstractParser<HelloBaalRequest>() {
      public HelloBaalRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloBaalRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloBaalRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloBaalRequest> getParserForType() {
      return PARSER;
    }

    public com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HelloBaalResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zohar.sample.HelloBaalResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string response = 1;</code>
     */
    java.lang.String getResponse();
    /**
     * <code>string response = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseBytes();

    /**
     * <code>int32 errorcode = 2;</code>
     */
    int getErrorcode();
  }
  /**
   * Protobuf type {@code zohar.sample.HelloBaalResponse}
   */
  public  static final class HelloBaalResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:zohar.sample.HelloBaalResponse)
      HelloBaalResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HelloBaalResponse.newBuilder() to construct.
    private HelloBaalResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HelloBaalResponse() {
      response_ = "";
      errorcode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HelloBaalResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              response_ = s;
              break;
            }
            case 16: {

              errorcode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xenoblade.zohar.sample.baal.api.Baal.internal_static_zohar_sample_HelloBaalResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xenoblade.zohar.sample.baal.api.Baal.internal_static_zohar_sample_HelloBaalResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse.class, com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private volatile java.lang.Object response_;
    /**
     * <code>string response = 1;</code>
     */
    public java.lang.String getResponse() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        response_ = s;
        return s;
      }
    }
    /**
     * <code>string response = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseBytes() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        response_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private int errorcode_;
    /**
     * <code>int32 errorcode = 2;</code>
     */
    public int getErrorcode() {
      return errorcode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, response_);
      }
      if (errorcode_ != 0) {
        output.writeInt32(2, errorcode_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, response_);
      }
      if (errorcode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errorcode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse)) {
        return super.equals(obj);
      }
      com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse other = (com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse) obj;

      boolean result = true;
      result = result && getResponse()
          .equals(other.getResponse());
      result = result && (getErrorcode()
          == other.getErrorcode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorcode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zohar.sample.HelloBaalResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zohar.sample.HelloBaalResponse)
        com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xenoblade.zohar.sample.baal.api.Baal.internal_static_zohar_sample_HelloBaalResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xenoblade.zohar.sample.baal.api.Baal.internal_static_zohar_sample_HelloBaalResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse.class, com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse.Builder.class);
      }

      // Construct using com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        response_ = "";

        errorcode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xenoblade.zohar.sample.baal.api.Baal.internal_static_zohar_sample_HelloBaalResponse_descriptor;
      }

      public com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse getDefaultInstanceForType() {
        return com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse.getDefaultInstance();
      }

      public com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse build() {
        com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse buildPartial() {
        com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse result = new com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse(this);
        result.response_ = response_;
        result.errorcode_ = errorcode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse) {
          return mergeFrom((com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse other) {
        if (other == com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse.getDefaultInstance()) return this;
        if (!other.getResponse().isEmpty()) {
          response_ = other.response_;
          onChanged();
        }
        if (other.getErrorcode() != 0) {
          setErrorcode(other.getErrorcode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object response_ = "";
      /**
       * <code>string response = 1;</code>
       */
      public java.lang.String getResponse() {
        java.lang.Object ref = response_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          response_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string response = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseBytes() {
        java.lang.Object ref = response_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          response_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response = 1;</code>
       */
      public Builder setResponse(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string response = 1;</code>
       */
      public Builder clearResponse() {
        
        response_ = getDefaultInstance().getResponse();
        onChanged();
        return this;
      }
      /**
       * <code>string response = 1;</code>
       */
      public Builder setResponseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        response_ = value;
        onChanged();
        return this;
      }

      private int errorcode_ ;
      /**
       * <code>int32 errorcode = 2;</code>
       */
      public int getErrorcode() {
        return errorcode_;
      }
      /**
       * <code>int32 errorcode = 2;</code>
       */
      public Builder setErrorcode(int value) {
        
        errorcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 errorcode = 2;</code>
       */
      public Builder clearErrorcode() {
        
        errorcode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:zohar.sample.HelloBaalResponse)
    }

    // @@protoc_insertion_point(class_scope:zohar.sample.HelloBaalResponse)
    private static final com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse();
    }

    public static com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HelloBaalResponse>
        PARSER = new com.google.protobuf.AbstractParser<HelloBaalResponse>() {
      public HelloBaalResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HelloBaalResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HelloBaalResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HelloBaalResponse> getParserForType() {
      return PARSER;
    }

    public com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  /**
   * Protobuf service {@code zohar.sample.BaalService}
   */
  public static abstract class BaalService
      implements com.google.protobuf.Service {
    protected BaalService() {}

    public interface Interface {
      /**
       * <code>rpc HelloBaal(.zohar.sample.HelloBaalRequest) returns (.zohar.sample.HelloBaalResponse);</code>
       */
      public abstract void helloBaal(
          com.google.protobuf.RpcController controller,
          com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest request,
          com.google.protobuf.RpcCallback<com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new BaalService() {
        @java.lang.Override
        public  void helloBaal(
            com.google.protobuf.RpcController controller,
            com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest request,
            com.google.protobuf.RpcCallback<com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse> done) {
          impl.helloBaal(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.helloBaal(controller, (com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc HelloBaal(.zohar.sample.HelloBaalRequest) returns (.zohar.sample.HelloBaalResponse);</code>
     */
    public abstract void helloBaal(
        com.google.protobuf.RpcController controller,
        com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest request,
        com.google.protobuf.RpcCallback<com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.xenoblade.zohar.sample.baal.api.Baal.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.helloBaal(controller, (com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest)request,
            com.google.protobuf.RpcUtil.<com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.xenoblade.zohar.sample.baal.api.Baal.BaalService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void helloBaal(
          com.google.protobuf.RpcController controller,
          com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest request,
          com.google.protobuf.RpcCallback<com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse.class,
            com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse helloBaal(
          com.google.protobuf.RpcController controller,
          com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse helloBaal(
          com.google.protobuf.RpcController controller,
          com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.xenoblade.zohar.sample.baal.api.Baal.HelloBaalResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:zohar.sample.BaalService)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zohar_sample_HelloBaalRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zohar_sample_HelloBaalRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zohar_sample_HelloBaalResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_zohar_sample_HelloBaalResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027zohar/sample/baal.proto\022\014zohar.sample\032" +
      "\027zohar/sample/enum.proto\"#\n\020HelloBaalReq" +
      "uest\022\017\n\007request\030\001 \001(\t\"8\n\021HelloBaalRespon" +
      "se\022\020\n\010response\030\001 \001(\t\022\021\n\terrorcode\030\002 \001(\0052" +
      "]\n\013BaalService\022N\n\tHelloBaal\022\036.zohar.samp" +
      "le.HelloBaalRequest\032\037.zohar.sample.Hello" +
      "BaalResponse\"\000B0\n#com.xenoblade.zohar.sa" +
      "mple.baal.apiB\004BaalP\000\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xenoblade.zohar.sample.api.Enum.getDescriptor(),
        }, assigner);
    internal_static_zohar_sample_HelloBaalRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zohar_sample_HelloBaalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zohar_sample_HelloBaalRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_zohar_sample_HelloBaalResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zohar_sample_HelloBaalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_zohar_sample_HelloBaalResponse_descriptor,
        new java.lang.String[] { "Response", "Errorcode", });
    com.xenoblade.zohar.sample.api.Enum.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
